const express = require('express')
const router = express.Router()
const userRouter = require('./userRouter')
const productRouter = require('./productRouter')
const categoryRouter = require('./categoryRouter')
const bigCategoryRouter = require('./bigCategoryRouter')
const sizeRouter = require('./sizeRouter')
const typeRouter = require('./typeRouter')
const transactionRouter = require('./transactionRouter')
const analyticsRouter = require('./analyticsRouter')
const carouselRouter = require('./carouselRouter')
const reviewRouter = require('./reviewRouter')
router.use('/users', userRouter)
router.use('/products', productRouter)
router.use('/categories', categoryRouter)
router.use('/bigcategories', bigCategoryRouter)
router.use('/sizes', sizeRouter)
router.use('/types', typeRouter)
router.use('/transactions', transactionRouter)
router.use('/analytics', analyticsRouter)
router.use('/carousels', carouselRouter)
router.use('/reviews', reviewRouter)
module.exports = router
