-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 22:10:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clothes-store
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clothes-store` ;

-- -----------------------------------------------------
-- Schema clothes-store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clothes-store` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clothes-store` ;

-- -----------------------------------------------------
-- Table `clothes-store`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`type` (
  `int` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`int`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothes-store`.`big_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`big_category` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type_int` INT NOT NULL,
  PRIMARY KEY (`id`, `type_int`),
  INDEX `fk_big_category_type1_idx` (`type_int` ASC) VISIBLE,
  CONSTRAINT `fk_big_category_type1`
    FOREIGN KEY (`type_int`)
    REFERENCES `clothes-store`.`type` (`int`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothes-store`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`category` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `big_category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `big_category_id`),
  INDEX `fk_category_big_category1_idx` (`big_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_big_category1`
    FOREIGN KEY (`big_category_id`)
    REFERENCES `clothes-store`.`big_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothes-store`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`products` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `cover_image` VARCHAR(200) NULL DEFAULT NULL,
  `isActive` TINYINT NULL DEFAULT NULL,
  `isSale` TINYINT NULL DEFAULT NULL,
  `sale_price` VARCHAR(45) NULL DEFAULT NULL,
  `create_at` TIMESTAMP NULL DEFAULT NULL,
  `update_at` TIMESTAMP NULL DEFAULT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `clothes-store`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clothes-store`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`product_image` (
  `id` INT NOT NULL,
  `Products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `Products_id`),
  INDEX `fk_Product_image_Products1_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_image_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `clothes-store`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clothes-store`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`user` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clothes-store`.`user_wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`user_wishlist` (
  `User_id` BIGINT NOT NULL,
  `Products_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`User_id`, `Products_id`, `id`),
  INDEX `fk_User_has_Products_Products1_idx` (`Products_id` ASC) VISIBLE,
  INDEX `fk_User_has_Products_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Products_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `clothes-store`.`products` (`id`),
  CONSTRAINT `fk_User_has_Products_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `clothes-store`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clothes-store`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`transaction` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `create_at` TIMESTAMP NULL,
  `status` VARCHAR(45) NULL,
  `total` BIGINT NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `clothes-store`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothes-store`.`transaction_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`transaction_product` (
  `quantity` BIGINT NULL,
  `transaction_id` BIGINT NOT NULL,
  `products_id` BIGINT NOT NULL,
  PRIMARY KEY (`transaction_id`, `products_id`),
  INDEX `fk_order_product_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_product_Order1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `clothes-store`.`transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `clothes-store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothes-store`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`size` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothes-store`.`product_size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothes-store`.`product_size` (
  `products_id` BIGINT NOT NULL,
  `size_id` INT NOT NULL,
  `create_at` TIMESTAMP NULL,
  PRIMARY KEY (`products_id`, `size_id`),
  INDEX `fk_product_size_size1_idx` (`size_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_size_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `clothes-store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_size_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `clothes-store`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
